version: "3.8"

services:
  hamburg_academy_postgres:
    container_name: hamburg_academy_postgres
    image: "postgres:latest"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: hamburgIt
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - hamburg_academy_postgres_data:/var/lib/postgresql/data

  redis:
    container_name: hamburg_academy_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    container_name: hamburg_academy_minio
    image: quay.io/minio/minio
    ports:
      - "9100:9000"   # API port
      - "9101:9001"   # Console port
    volumes:
      - miniodata:/data
    environment:
      MINIO_ROOT_USER: hamburgItAcademy
      MINIO_ROOT_PASSWORD: hamburgAcademy2025
    command: server /data --console-address ":9001"

volumes:
  hamburg_academy_postgres_data:
  redis_data:
  miniodata: